services:
  - type: web
    name: leetcode-solver
    env: python
    buildCommand: "py -m pip install -r requirements.txt"
    startCommand: "py -m streamlit run app.py"
  - type: worker
    name: selenium-worker
    env: python
    buildCommand: "py -m pip install -r requirements.txt"
    startCommand: "py -m python selenium_script.py"
